#!/usr/bin/env bash
# Bootstrap (Part 1): seeds /exports/reports-2026-08.tar.bz2 with a small
# multi-file dataset. Does NOT create the gzip archive or the listing
# files -- that is the graded task.

set -eu

sudo mkdir -p /exports

STAGE=$(mktemp -d)

cat > "$STAGE/summary.csv" <<'EOF'
region,units_shipped,revenue
north,4210,182300.00
south,3110,140550.50
EOF

cat > "$STAGE/README.txt" <<'EOF'
Monthly export bundle - August 2026.
Generated by the reporting pipeline; treat as read-only once archived.
EOF

mkdir -p "$STAGE/raw"
cat > "$STAGE/raw/events.log" <<'EOF'
2026-08-01T00:03:11Z batch_start id=8391
2026-08-01T00:11:47Z batch_complete id=8391 rows=18420
EOF

( cd "$STAGE" && tar -cjf /tmp/reports-2026-08.tar.bz2 . )
sudo mv /tmp/reports-2026-08.tar.bz2 /exports/reports-2026-08.tar.bz2
sudo chown root:root /exports/reports-2026-08.tar.bz2

rm -rf "$STAGE"

# Content baseline so validation can prove the original was never modified.
sudo mkdir -p /var/lib/astrona-lab
sha256sum /exports/reports-2026-08.tar.bz2 | sudo tee /var/lib/astrona-lab/reports-2026-08.tar.bz2.sha256 > /dev/null
